<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pa19">
  <eClassifiers xsi:type="ecore:EClass" name="Game">
    <eOperations name="placePipe" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="row" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="col" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
    </eOperations>
    <eOperations name="skipPipe"/>
    <eOperations name="undoStep" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="updateState"/>
    <eOperations name="haswon" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="hasLost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numOfSteps" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="map" eType="#//GameMap"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pipeQueue" eType="#//GameMap"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="delayBar" eType="#//DelayBar"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cellStack" eType="#//CellStack"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cell" abstract="true">
    <eOperations name="toSingleChar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coord"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FillableCell" eSuperTypes="#//Cell">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pipe" eType="#//Pipe"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Wall" eSuperTypes="#//Cell"/>
  <eClassifiers xsi:type="ecore:EClass" name="TerminationCell" eSuperTypes="#//Cell">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pointingTo" eType="#//Direction"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//TerminationType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pipe">
    <eOperations name="getConnections" upperBound="-1" eType="#//Direction"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shape" eType="#//PipeShape"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PipeQueue">
    <eOperations name="peek" eType="#//Pipe"/>
    <eOperations name="consume"/>
    <eOperations name="undo">
      <eParameters name="pipe" eType="#//Pipe"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxGenLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="5" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="queue" upperBound="-1"
        eType="#//Pipe" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DelayBar">
    <eOperations name="countdown"/>
    <eOperations name="distance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CellStack">
    <eOperations name="push">
      <eParameters name="cell" eType="#//FillableCell"/>
    </eOperations>
    <eOperations name="pop" eType="#//FillableCell"/>
    <eOperations name="getUndoCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stack" upperBound="-1"
        eType="#//FillableCell" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Deserializer">
    <eOperations name="parseGame" eType="#//Game"/>
    <eOperations name="parseString" eType="#//CellGrid">
      <eParameters name="rows" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="cols" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="cellsRep" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Direction">
    <eLiterals name="UP"/>
    <eLiterals name="DOWN" value="1"/>
    <eLiterals name="LEFT" value="2"/>
    <eLiterals name="RIGHT" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Coordinate">
    <eOperations name="add" eType="#//Coordinate">
      <eParameters name="other" eType="#//Coordinate"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="row" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="col" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GameMap">
    <eOperations name="tryPlacePipe" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="coord" eType="#//Coordinate"/>
      <eParameters name="pipe" eType="#//Pipe"/>
    </eOperations>
    <eOperations name="undo">
      <eParameters name="coord" eType="#//Coordinate"/>
    </eOperations>
    <eOperations name="fillBeginTile"/>
    <eOperations name="fillTiles">
      <eParameters name="distance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="checkPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="hasLost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="display"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="row" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="col" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prevFilledTiles" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prevFilledDistance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="grid" eType="#//CellGrid"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceCell" eType="#//TerminationCell"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sinkCell" eType="#//TerminationCell"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filledTiles" upperBound="-1"
        eType="#//Coordinate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PipeShape">
    <eLiterals name="HORIZONTAL"/>
    <eLiterals name="VERTICAL" value="1"/>
    <eLiterals name="TOP_LEFT" value="2"/>
    <eLiterals name="TOP_RIGHT" value="3"/>
    <eLiterals name="BOTTOM_LEFT" value="4"/>
    <eLiterals name="BOTTOM_RIGHT" value="5"/>
    <eLiterals name="CROSS" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TerminationType">
    <eLiterals name="SOURCE"/>
    <eLiterals name="SINK" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CellGrid">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="row" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="col" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cells" upperBound="-1"
        eType="#//Cell" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
